name: CI for Kotlin multiplatform library 
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build libraries and sample app
      run: ./gradlew assembleDebug --info
    - name: Run ktlint with spotless
      run: ./gradlew spotlessKotlinCheck
    - name: Run unit tests
      run: ./gradlew :komol-core:allTests
